### ISSUE TITLE
issues downloading data

### ISSUE THREAD

**Issue by arjunroychowdhury** [blindmotion/normalizer#3]
Hi, the link https://yadi.sk/d/NJSeeOk5bYm7V offers the data to download using a service called Yandex. The zipped archive seems to be 35GB, but download stops after 4.5GB. I've tried on multiple connections (including FIOS), so I'm pretty sure its not the connection.

I was wondering if its possible to split the folders into separate ZIPs or offer some other means to download? Thanks.

**Comment by lamerman** [comment]
Hi, the interface is indeed quite strange. I would recommend you the following options:
- try to download not the whole dataset at once but for specific date. For example https://yadi.sk/d/NJSeeOk5bYm7V/Video/20140917 . The same for data other than video.
- register on yandex, install their yandex.disk client and save it to your disk. Then it should manage somehow to sync the data from cloud to your PC
- also Yandex.Disk supports webdav https://yandex.com/support/disk/webdav.html , so maybe it's possible to navigate easily using it instead

**Comment by arjunroychowdhury** [comment]
Thanks - I'm going ahead with individual downloads. Unfortunately, yandex disk only gives us 10GB which is not sufficient to clone your data and webdav only works with your own acct (so I can't use it to download yours). 

Thank you for your excellent work!

**Comment by lamerman** [comment]
As I remember they recently announced that shared folders will no longer
consume your own space. But I have never checked it myself.
